{
  const POSITION_GROUPS = [
    { code: 'QB', name: 'Quarterback', slots: 2 },
    { code: 'RB', name: 'Running back', slots: 2 },
    { code: 'WR', name: 'Wide receiver', slots: 4 },
    { code: 'TE', name: 'Tight end', slots: 3 },
    { code: 'OL', name: 'Offensive line', slots: 5 },
    { code: 'DL', name: 'Defensive line', slots: 5 },
    { code: 'LB', name: 'Linebacker', slots: 4 },
    { code: 'CB', name: 'Cornerback', slots: 4 },
    { code: 'S', name: 'Safety', slots: 2 },
  ];
  const POSITIONS = POSITION_GROUPS.flatMap((group) =>
    Array.from({ length: group.slots }, (_, index) => ({ code: group.code, name: group.name, depth: index + 1 })),
  );
  const SALARY_CAP = 26000;

  const OFFENSE = [
    {
      id: 'inside-zone',
      name: 'Inside Zone',
      icon: '🦬',
      group: 'run',
      kind: 'run',
      base: 3,
      spread: 10,
      detail: 'Patient run between the tackles',
    },
    {
      id: 'power-run',
      name: 'Power Run',
      icon: '💪',
      group: 'run',
      kind: 'run',
      personnel: '12',
      base: 4,
      spread: 11,
      detail: 'Two tight ends lead a downhill run',
    },
    {
      id: 'outside-stretch',
      name: 'Outside Stretch',
      icon: '🌿',
      group: 'run',
      kind: 'run',
      base: 3,
      spread: 15,
      detail: 'Race the defense to the edge',
    },
    {
      id: 'draw',
      name: 'Draw Play',
      icon: '🎣',
      group: 'run',
      kind: 'run',
      base: 4,
      spread: 13,
      detail: 'Invite the rush, then run',
    },
    {
      id: 'qb-sneak',
      carrier: ['QB', 0],
      name: 'QB Sneak',
      icon: '🐾',
      group: 'run',
      kind: 'run',
      personnel: '13',
      base: 1,
      spread: 5,
      detail: 'Three tight ends crowd the goal line',
    },
    {
      id: 'counter-run',
      name: 'Counter Run',
      icon: '↪️',
      group: 'run',
      kind: 'run',
      base: 4,
      spread: 13,
      detail: 'Step one way, cut back behind the line',
    },
    {
      id: 'read-option',
      carrier: ['QB', 0],
      name: 'Read Option',
      icon: '🔀',
      group: 'run',
      kind: 'run',
      base: 5,
      spread: 15,
      detail: 'Quarterback reads the edge defender',
    },
    {
      id: 'halfback-dive',
      name: 'HB Dive',
      icon: '⬆️',
      group: 'run',
      kind: 'run',
      personnel: '12',
      base: 3,
      spread: 8,
      detail: 'Quick downhill handoff behind two tight ends',
    },
    {
      id: 'pitch-toss',
      name: 'Pitch Toss',
      icon: '↗️',
      group: 'run',
      kind: 'run',
      base: 4,
      spread: 16,
      detail: 'Pitch to the back toward open space',
    },
    {
      id: 'trap-run',
      name: 'Trap Run',
      icon: '🪤',
      group: 'run',
      kind: 'run',
      base: 4,
      spread: 12,
      detail: 'Invite a rusher through, then trap them',
    },
    {
      id: 'quick-slant',
      name: 'Quick Slant',
      icon: '⚡',
      group: 'pass',
      kind: 'short',
      base: 6,
      spread: 10,
      detail: 'Fast timing route',
    },
    {
      id: 'curl-routes',
      name: 'Curl Routes',
      icon: '↩️',
      group: 'pass',
      kind: 'short',
      base: 7,
      spread: 11,
      detail: 'Reliable sideline throw',
    },
    {
      id: 'screen-pass',
      carrier: ['RB', 0],
      name: 'Screen Pass',
      icon: '🫧',
      group: 'pass',
      kind: 'short',
      base: 6,
      spread: 14,
      detail: 'Punish an aggressive rush',
    },
    {
      id: 'drag-cross',
      name: 'Drag Cross',
      icon: '➰',
      group: 'pass',
      kind: 'short',
      base: 7,
      spread: 11,
      detail: 'Receivers cross underneath coverage',
    },
    {
      id: 'out-route',
      name: 'Out Route',
      icon: '↗️',
      group: 'pass',
      kind: 'short',
      base: 6,
      spread: 12,
      detail: 'Quick break toward the sideline',
    },
    {
      id: 'mesh',
      name: 'Mesh',
      icon: '✕',
      group: 'pass',
      kind: 'short',
      base: 7,
      spread: 12,
      detail: 'Two shallow crossers create traffic',
    },
    {
      id: 'shovel-pass',
      carrier: ['TE', 0],
      name: 'Shovel Pass',
      icon: '🥄',
      group: 'pass',
      kind: 'short',
      base: 5,
      spread: 11,
      detail: 'Flip the ball under the pass rush',
    },
    {
      id: 'te-seam',
      carrier: ['TE', 0],
      name: 'TE Seam',
      icon: '🪡',
      group: 'pass',
      kind: 'medium',
      base: 11,
      spread: 15,
      detail: 'Split the safeties',
    },
    {
      id: 'play-action',
      name: 'Play Action',
      icon: '🎭',
      group: 'pass',
      kind: 'medium',
      base: 12,
      spread: 16,
      detail: 'Sell the run, throw behind it',
    },
    {
      id: 'post-route',
      name: 'Post Route',
      icon: '📮',
      group: 'pass',
      kind: 'medium',
      base: 14,
      spread: 16,
      detail: 'Attack the gap between deep defenders',
    },
    {
      id: 'wheel-route',
      carrier: ['RB', 1],
      name: 'Wheel Route',
      icon: '🎡',
      group: 'pass',
      kind: 'medium',
      personnel: '21',
      base: 12,
      spread: 18,
      detail: 'Second back turns upfield along the sideline',
    },
    {
      id: 'flood',
      name: 'Flood',
      icon: '🌊',
      group: 'pass',
      kind: 'medium',
      base: 11,
      spread: 17,
      detail: 'Layer three routes on one sideline',
    },
    {
      id: 'corner-route',
      name: 'Corner Route',
      icon: '📐',
      group: 'pass',
      kind: 'medium',
      base: 13,
      spread: 16,
      detail: 'Break toward the deep corner',
    },
    {
      id: 'deep-shot',
      name: 'Deep Shot',
      icon: '🚀',
      group: 'pass',
      kind: 'deep',
      personnel: '10',
      base: 22,
      spread: 20,
      detail: 'Four receivers stretch the defense',
    },
    {
      id: 'hail-mary',
      name: 'Hail Mary',
      icon: '🌠',
      group: 'pass',
      kind: 'deep',
      base: 32,
      spread: 26,
      detail: 'Desperation ball downfield',
    },
    {
      id: 'double-move',
      name: 'Double Move',
      icon: '〽️',
      group: 'pass',
      kind: 'deep',
      base: 24,
      spread: 22,
      detail: 'Fake a short route, break deep',
    },
    {
      id: 'four-verticals',
      name: 'Four Verticals',
      icon: '⬆️',
      group: 'pass',
      kind: 'deep',
      personnel: '10',
      base: 22,
      spread: 22,
      detail: 'Send all four receivers downfield',
    },
    {
      id: 'jet-sweep',
      carrier: ['WR', 0],
      name: 'Jet Sweep',
      icon: '🌪️',
      group: 'trick',
      kind: 'run',
      base: 5,
      spread: 17,
      detail: 'Receiver takes the handoff',
    },
    {
      id: 'reverse',
      carrier: ['WR', 0],
      name: 'Reverse',
      icon: '🔄',
      group: 'trick',
      kind: 'run',
      base: 10,
      spread: 21,
      detail: 'Send pursuit the wrong way',
    },
    {
      id: 'flea-flicker',
      name: 'Flea Flicker',
      icon: '🪄',
      group: 'trick',
      kind: 'trick',
      base: 18,
      spread: 25,
      detail: 'Double handoff into a pass',
    },
    {
      id: 'qb-scramble',
      carrier: ['QB', 0],
      name: 'QB Scramble',
      icon: '🏃',
      group: 'trick',
      kind: 'run',
      base: 4,
      spread: 13,
      detail: 'Let the passer find a lane',
    },
    {
      id: 'end-around',
      carrier: ['WR', 0],
      name: 'End Around',
      icon: '🌀',
      group: 'trick',
      kind: 'run',
      base: 5,
      spread: 17,
      detail: 'Wideout circles behind the quarterback',
    },
    {
      id: 'rpo-slant',
      name: 'RPO Slant',
      icon: '⚔️',
      group: 'trick',
      kind: 'short',
      base: 7,
      spread: 13,
      detail: 'Read the box, then hand off or throw',
    },
    {
      id: 'wildcat',
      name: 'Wildcat',
      icon: '🐾',
      group: 'trick',
      kind: 'run',
      personnel: '21',
      base: 6,
      spread: 16,
      detail: 'Direct snap to the back with a second back leading',
    },
    {
      id: 'double-pass',
      passer: ['QB', 1],
      name: 'Double Pass',
      icon: '🎲',
      group: 'trick',
      kind: 'trick',
      personnel: '2QB',
      base: 17,
      spread: 22,
      detail: 'The second QB throws after a lateral',
    },
    {
      id: 'goal-line-stack',
      name: 'Goal-Line Stack',
      icon: '🚧',
      group: 'run',
      kind: 'run',
      personnel: '13',
      base: 2,
      spread: 7,
      detail: 'Three tight ends jam the middle',
    },
    {
      id: 'punt',
      name: 'Punt',
      icon: '🦵',
      group: 'special',
      kind: 'punt',
      base: 0,
      spread: 0,
      detail: 'Flip the field on fourth down',
    },
    {
      id: 'field-goal',
      name: 'Field Goal',
      icon: '🎯',
      group: 'special',
      kind: 'kick',
      base: 0,
      spread: 0,
      detail: 'Three points if it is good',
    },
  ].map((play) => ({
    carrier: play.kind === 'run' ? ['RB', 0] : ['kick', 'punt'].includes(play.kind) ? ['QB', 0] : ['WR', 0],
    passer: ['QB', 0],
    ...play,
  }));

  const DEFENSE = [
    {
      id: 'cover-2',
      name: 'Cover 2',
      icon: '🛡️',
      detail: 'Two deep defenders',
      strengths: ['medium', 'deep'],
      weakness: 'run',
    },
    { id: 'cover-3', name: 'Cover 3', icon: '☂️', detail: 'Three deep zones', strengths: ['deep'], weakness: 'short' },
    {
      id: 'cover-4',
      name: 'Cover 4',
      icon: '🌧️',
      detail: 'Blanket long routes',
      strengths: ['deep', 'trick'],
      weakness: 'run',
    },
    {
      id: 'man',
      name: 'Man Coverage',
      icon: '👁️',
      detail: 'Match every receiver',
      strengths: ['short', 'medium'],
      weakness: 'run',
    },
    {
      id: 'press',
      name: 'Press Man',
      icon: '✋',
      detail: 'Jam receivers early',
      strengths: ['short'],
      weakness: 'deep',
    },
    {
      id: 'blitz',
      name: 'Blitz',
      icon: '💥',
      detail: 'Send extra rushers',
      strengths: ['deep', 'medium'],
      weakness: 'short',
    },
    { id: 'run-stuff', name: 'Run Stuff', icon: '🧱', detail: 'Stack the box', strengths: ['run'], weakness: 'deep' },
    {
      id: 'spy',
      name: 'QB Spy',
      icon: '🎯',
      detail: 'Track the passer',
      strengths: ['trick', 'run'],
      weakness: 'medium',
    },
    { id: 'prevent', name: 'Prevent', icon: '🌊', detail: 'Keep it in front', strengths: ['deep'], weakness: 'short' },
    {
      id: 'zone-blitz',
      name: 'Zone Blitz',
      icon: '🌀',
      detail: 'Disguised pressure',
      strengths: ['medium', 'trick'],
      weakness: 'run',
    },
    {
      id: 'nickel',
      name: 'Nickel',
      icon: '🪙',
      detail: 'Extra defensive back',
      strengths: ['short', 'medium'],
      weakness: 'run',
    },
    {
      id: 'goal-line',
      name: 'Goal Line',
      icon: '🚧',
      detail: 'Heavy short-yardage front',
      strengths: ['run'],
      weakness: 'deep',
    },
    {
      id: 'cover-1',
      name: 'Cover 1',
      icon: '☝️',
      detail: 'Single high safety; tight man underneath',
      strengths: ['short'],
      weakness: 'deep',
    },
    {
      id: 'cover-6',
      name: 'Cover 6',
      icon: '6️⃣',
      detail: 'Split-field zones; resist deep posts',
      strengths: ['deep', 'medium'],
      weakness: 'run',
    },
    {
      id: 'tampa-2',
      name: 'Tampa 2',
      icon: '🌴',
      detail: 'Linebacker drops deep through the middle',
      strengths: ['medium'],
      weakness: 'short',
    },
    {
      id: 'bear-front',
      name: 'Bear Front',
      icon: '🐻',
      detail: 'Crowd the line to shut down inside runs',
      strengths: ['run'],
      weakness: 'deep',
    },
    {
      id: 'edge-contain',
      name: 'Edge Contain',
      icon: '🪤',
      detail: 'Set a hard edge against sweeps and scrambles',
      strengths: ['run', 'trick'],
      weakness: 'medium',
    },
    {
      id: 'robber',
      name: 'Robber',
      icon: '🦝',
      detail: 'Safety jumps crossing and slant routes',
      strengths: ['short', 'medium'],
      weakness: 'deep',
    },
    {
      id: 'double-wide',
      name: 'Double Wide',
      icon: '👥',
      detail: 'Bracket the two outside receivers',
      strengths: ['deep'],
      weakness: 'run',
    },
    {
      id: 'cover-0',
      name: 'Cover 0',
      icon: '0️⃣',
      detail: 'All-out pressure with no deep help',
      strengths: ['short', 'medium'],
      weakness: 'deep',
    },
    {
      id: 'fire-zone',
      name: 'Fire Zone',
      icon: '🔥',
      detail: 'Pressure one side, rotate coverage behind it',
      strengths: ['medium', 'trick'],
      weakness: 'run',
    },
    {
      id: 'quarters-match',
      name: 'Quarters Match',
      icon: '♟️',
      detail: 'Match vertical routes from a four-deep shell',
      strengths: ['deep', 'trick'],
      weakness: 'run',
    },
    {
      id: 'dime',
      name: 'Dime',
      icon: '💠',
      detail: 'Flood the secondary with cover defenders',
      strengths: ['deep', 'medium'],
      weakness: 'run',
    },
    {
      id: 'run-blitz',
      name: 'Run Blitz',
      icon: '🚨',
      detail: 'Shoot gaps before blockers can set',
      strengths: ['run'],
      weakness: 'deep',
    },
    {
      id: 'red-zone-bracket',
      name: 'Red Zone Bracket',
      icon: '🧲',
      detail: 'Double key targets near the goal line',
      strengths: ['short', 'medium'],
      weakness: 'run',
    },
    {
      id: 'contain-man',
      name: 'Contain Man',
      icon: '🔒',
      detail: 'Man coverage with disciplined edge defenders',
      strengths: ['run', 'short'],
      weakness: 'deep',
    },
  ];

  if (typeof module !== 'undefined') module.exports = { POSITION_GROUPS, POSITIONS, SALARY_CAP, OFFENSE, DEFENSE };
  else Object.assign((window.Pokeballers ||= {}), { POSITION_GROUPS, POSITIONS, SALARY_CAP, OFFENSE, DEFENSE });
}
